[workspace]
resolver = "2"
members = [
    "PostgresWire/main",
    "PostgresWire/steps",
    "Server/main",
    "QualityEngineering/main",
    "QualityEngineering/steps",
    "QualityEngineering/goose",
    "QualityEngineering/cucumber-rs",
    "QualityEngineering/cucumber-rs/codegen",
]
