package io.beandev.datorum.schema.jdbc;

import javax.sql.DataSource;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import io.beandev.datorum.schema.SchemaRepository;

public class JdbcSchemaRepository implements SchemaRepository {
    private final DataSource dataSource;

    public JdbcSchemaRepository(DataSource ds) {
        dataSource = ds;
    }

    @Override
    public void createBaseTables() {
        try (Connection conn = dataSource.getConnection()) {
            try {

                // Create schemas
                String sql = """
                        CREATE SCHEMA IF NOT EXISTS \"datorum_schema\";
                        CREATE SCHEMA IF NOT EXISTS \"datorum_migrations\";
                        CREATE SCHEMA IF NOT EXISTS \"datorum_events\";
                        CREATE SCHEMA IF NOT EXISTS \"datorum_snapshots\";
                        CREATE SCHEMA IF NOT EXISTS \"datorum_views\";
                        """;
                try (Statement stmt = conn.createStatement()) {
                    stmt.execute(sql);
                }

                // Creating tables
                sql = """
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."app" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."table_infix" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            reference_id BIGINT,
                            table_infix VARCHAR(30) NOT NULL
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."cluster" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_migrations"."migration" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_migrations"."migration_command" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            action VARCHAR(25) NOT NULL,
                            migration_id BIGINT NOT NULL,
                            FOREIGN KEY (migration_id) REFERENCES "datorum_migrations"."migration"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_migrations"."migration_event" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            migration_command_id BIGINT NOT NULL,
                            FOREIGN KEY (migration_command_id) REFERENCES "datorum_migrations"."migration_command"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."context" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            app_id BIGINT NOT NULL,
                            FOREIGN KEY (app_id) REFERENCES "datorum_schema"."app"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."aggregate" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            context_id BIGINT NOT NULL,
                            FOREIGN KEY (context_id) REFERENCES "datorum_schema"."context"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."entity" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            aggregate_id BIGINT UNIQUE NOT NULL,
                            table_infix_id BIGINT,
                            is_root BOOLEAN UNIQUE,
                            FOREIGN KEY (aggregate_id) REFERENCES "datorum_schema"."aggregate"(id),
                            FOREIGN KEY (table_infix_id) REFERENCES "datorum_schema"."table_infix"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."attribute" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            datatype_name VARCHAR(25) NOT NULL,
                            datatype_length INT,
                            datatype_scale INT,
                            entity_id BIGINT NOT NULL,
                            table_infix_id BIGINT,
                            FOREIGN KEY (entity_id) REFERENCES "datorum_schema"."entity"(id),
                            FOREIGN KEY (table_infix_id) REFERENCES "datorum_schema"."table_infix"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."datasource" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            cluster_id BIGINT,
                            FOREIGN KEY (cluster_id) REFERENCES "datorum_schema"."cluster"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."shard" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            datasource_id BIGINT,
                            FOREIGN KEY (datasource_id) REFERENCES "datorum_schema"."datasource"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."sharding" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            is_query BOOLEAN,
                            shard_id BIGINT,
                            FOREIGN KEY (shard_id) REFERENCES "datorum_schema"."shard"(id)
                        );
                        CREATE TABLE IF NOT EXISTS "datorum_schema"."sharding_aggregate" (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(250) NOT NULL,
                            size SMALLINT,
                            sharding_id BIGINT,
                            aggregate_id BIGINT,
                            FOREIGN KEY (sharding_id) REFERENCES "datorum_schema"."sharding"(id),
                            FOREIGN KEY (aggregate_id) REFERENCES "datorum_schema"."aggregate"(id)
                        );
                        """;

                try (Statement stmt = conn.createStatement()) {
                    stmt.execute(sql);
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
