[package]
name = "datorum-server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
pgwire = "0.29.1"

# https://doc.rust-lang.org/cargo/reference/manifest.html